[package]
name = "CetusAggregatorV2"
version = "0.1.1"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
published-at = "0x2d25c227be42b1748f916493e36f61f3b8f42664a0f709e55d4e6887570010c8"
# published-at = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.23.1", override = true }
SuiSystem = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-system", rev = "mainnet-v1.23.1", override = true }
MoveSTL = { git = "https://github.com/CetusProtocol/move-stl.git", rev = "mainnet-v1.3.0", override = true }
IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", rev = "mainnet-v1.3.0", override = true }
CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/cetus_clmm", rev = "mainnet-v1.50.0", override = true }
DeepBook = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/deepbook", rev = "mainnet-v1.23.1" }
KriyaAmm = { local = "../../externals/kriya-amm" }
KriyaClmm = { local = "../../externals/kriya-clmm" }
FlowxClmm = { local = "../../externals/flowx-clmm" }
FlowxAMM = { local = "../../externals/flowx-amm" }
TurbosDex = { local = "../../externals/turbos-dex" }
AftermathAMM = { local = "../../externals/aftermath/aftermath-amm" }
ProtocolFeeVault = { local = "../../externals/aftermath/amm-protocol-fee-vault" }
InsuranceFund = { local = "../../externals/aftermath/amm-insurance-fund" }
ReferralVault = { local = "../../externals/aftermath/amm-referral-vault" }
StakingRefer = { local = "../../externals/aftermath/staking-refer" }
Afsui = { local = "../../externals/aftermath/staking" }
Hasui = { local = "../../externals/hasui" }
Vsui = { local = "../../externals/vsui" }
BlueMove = { local = "../../externals/bluemove" }
deepbookv3 = { local = "../../externals/deepbookv3-old/deepbook" }
token = { local = "../../externals/deepbookv3-old/token" }


[addresses]
cetus_aggregator_v2 = "0xeffc8ae61f439bb34c9b905ff8f29ec56873dcedf81c7123ff2f1f67c45ec302"
# cetus_aggregator_v2 = "0x0"
